project:
  type: book
  output-dir: docs

book:
  title: "Honey Drip Progress Journal"
  repo-url: https://github.com/pjournal/mef06g-honey-drip
  chapters:
    - index.qmd
    - assignment1.qmd
    - preprocessing.qmd
    - ExploratoryDataAnalysis.qmd
    - finalreport.qmd
    - shinyapp.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

