---
title: "Exploratory Data Analysis"
output: html_document
date: "2022-11-29"
---

## Necessary libraries 

```{r}
#| warning: false
library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate)
library(tidyr)
library(zoo)
library(janitor)
library(reactable)
library(data.table)
library(ggplot2)
```



## Importing data

We are importing construction cost index, Turnover rate, usd to tl exchange rate, House sales to foreigners data sets, .................. .
```{r}
ConsIndex <- readRDS("Datards/ConsIndex.rds")
Turnover <- readRDS("Datards/Turnover.rds")
House_sales_to_foreigners_month <- readRDS("Datards/House_sales_to_foreigners_month.rds")
House_sales_to_foreigners_year <- readRDS("Datards/House_sales_to_foreigners_year.rds")

monthly_usd_to_try <- read_excel("data/monthly_usd_to_try.xls")
monthly_usd_to_try$month <- as.Date(monthly_usd_to_try$month)
monthly_usd_to_try$month <- format(monthly_usd_to_try$month,"%Y-%b-%d")

PATH <- "data/House Sales by Provinces.xls"
house_sales_by_provinces <- read_excel(PATH, range = cell_rows(14:129), col_names = names(read_excel(PATH, skip = 2))) 

total_sales_by_year <- aggregate(house_sales_by_provinces[3], house_sales_by_provinces[1], FUN=sum)

House_sales_to_foreigners_month <- read_excel("data/House sales to foreigners.xls", 
                                                   sheet = "Month")
House_sales_to_foreigners_month$Month <- match(House_sales_to_foreigners_month$Month, month.name)

House_sales_to_foreigners_month$Date <- as.yearmon(paste(House_sales_to_foreigners_month$Year, House_sales_to_foreigners_month$Month), "%Y %m")

```


```{r}
ggplot(House_sales_to_foreigners_month, aes(Date)) + 
  geom_line(aes(y = Total, colour = "Total")) + 
  geom_line(aes(y = `Sales to foreigners`, colour = "Sales To Foreigners"))

ggplot(House_sales_to_foreigners_month, aes(Date)) + 
  geom_line(aes(y = `Share (%)`, colour = "Share (%)"))



"Finding construction cost index yearly mean to compare"
ConsIndexYear <- ConsIndex %>% group_by(Year) %>% summarise(Construction_cost_mean = mean(index, na.rm = TRUE))
TurnoverYear <- Turnover %>% group_by(Year) %>% summarise(Turnover_mean = mean(`seasonal and calendar adjusted
Index`))

ConsIndexYear %>% left_join(TurnoverYear, by = "Year") %>% ggplot(aes(Year)) +
  geom_line(aes(y = Construction_cost_mean, colour = "Construction cost mean")) + 
  geom_line(aes(y = Turnover_mean, colour = "Turnover mean"))+
  labs(title="Construction cost and Turnover index yearly mean comparison")+
  xlab("Year") +
  ylab("Index")


"USD to TL Exchange rate"
ggplot(monthly_usd_to_try, aes(x = `month`, y = `usd_rate`, group = 1)) +
  geom_line(linetype="solid", color="red", size=2) +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
 labs(title="USD to TL Exchange rate")+
  xlab("Year") +
  ylab("Xrate")



```


```{r}
house_sales_by_provinces  <- house_sales_by_provinces  %>%
    fill(colnames(house_sales_by_provinces[1]), .direction = "downup")

# Creating Time Series Object for House Sales by Proviences
total_hs_ts <- ts(house_sales_by_provinces[3],start=c(2013,1),frequency=12)

options(repr.plot.width=21, repr.plot.height=8)
plot(total_hs_ts)
```


```{r}
# Monthly usd to try graph
monthly_usd_to_try <- read_excel("data/monthly_usd_to_try.xls")

# Monhtly usd rate preprocessing
monthly_usd_to_try$month <- as.Date(monthly_usd_to_try$month)
colnames(monthly_usd_to_try) <- c("date","value")

ggplot(data=monthly_usd_to_try, aes(x=date, y=value, group=1)) +
  geom_line()+
  geom_point()
```




```{r}
# Monthly cost index
construction_cost_index <- read_excel("data/construction_cost_index_by_industries_and_cost_groups_preprocessed.xls")

# Monhtly cost index preprocessing
construction_cost_index$date <- as.Date(construction_cost_index$date)
colnames(construction_cost_index) <- c("date","cost_type","value","material","labour")

cost_index = construction_cost_index %>% 
  filter(cost_type=="construction") %>%
  group_by(date) %>%
  summarize(value=sum(value))

# There are significant relationship between USD/TRY Rate and Cost Index
ggplot(data=cost_index, aes(x=date, y=value, group=1)) +
  geom_line()+
  geom_point()
```




```{r}
# Yillik satista ulkeler
library(readxl)
HSTFBN <- read_excel("data/HSTFBN.xls", sheet = "FOREIGNERS BY NATIONALITIES")

total_sale_by_country <- HSTFBN %>% group_by(year,country) %>% summarise(sum=sum(total))


# 2017'den sonra Iran, Irak'i geciyor.
# 2021'den 2022'ye gecerken rusya da yuksek bir artis var.

ggplot(data=total_sale_by_country,aes(x=year,y=sum,fill=country)) +
  geom_bar(stat="identity",position = "dodge")
```




```{r}
house_sales_by_districts_preprocessed <- read_excel("data/house_sales_by_districts_preprocessed.xls")

house_sales <- house_sales_by_districts_preprocessed %>%
  group_by(year) %>%
  summarise(morgaged=sum(mortgaged), total=sum(total), first_hand=sum(first_hand), second_hand=sum(second_hand))


ggplot(data=house_sales,aes(x=year),group = 1 ) +
  geom_line(aes(y=morgaged,color='morgaged')) +
  geom_line(aes(y=total,color='total'))+
  xlab("Year")+
  ylab("Values")
```




```{r}
house_sales_by_districts_preprocessed <- read_excel("data/house_sales_by_districts_preprocessed.xls")

house_sales <- house_sales_by_districts_preprocessed %>%
  group_by(year) %>%
  summarise(morgaged=sum(mortgaged), total=sum(total), first_hand=sum(first_hand), second_hand=sum(second_hand))


ggplot(data=house_sales,aes(x=year),group = 1 ) +
  geom_line(aes(y=first_hand,color='first_hand')) +
  geom_line(aes(y=second_hand,color='second_hand')) +
  xlab("Year")+
  ylab("Values")
```


```{r}
# Monthly usd to try graph
monthly_usd_to_try <- read_excel("~/Work/mef06g-honey-drip/data/monthly_usd_to_try.xls")

# Monhtly usd rate preprocessing
monthly_usd_to_try$month <- as.Date(monthly_usd_to_try$month)
colnames(monthly_usd_to_try) <- c("date","value")

# Monthly cost index
construction_cost_index <- read_excel("~/Work/mef06g-honey-drip/data/construction_cost_index_by_industries_and_cost_groups_preprocessed.xls")

# Monhtly cost index preprocessing
construction_cost_index$date <- as.Date(construction_cost_index$date)
colnames(construction_cost_index) <- c("date","cost_type","value","material","labour")

cost_index = construction_cost_index %>% 
  filter(cost_type=="construction") %>%
  group_by(date) %>%
  summarize(value=sum(value))

# There are significant relationship between USD/TRY Rate and Cost Index
ggplot(data=cost_index, aes(x=date, y=value, group=1)) +
  geom_line()+
  geom_point()

ggplot(data=usd_rate, aes(x=date, y=value, group=1)) +
  geom_line()+
  geom_point()
```

