---
title: "Preprocessing"
output: html_document
date: "2022-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preprocessing


## Necessary libraries

```{r}
library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate)
library(zoo)

```

## PREPROCESS

```{r}
"First part of cleaning data done in excel then I use Pivot longer Function"

ConsIndex <- read_excel("data/Constructioncost.xls", 
                             sheet = "Index")
ConsIndex <- pivot_longer(ConsIndex,2:13,names_to = "Month", values_to = "index")
ConsIndex$Month <- match(ConsIndex$Month, month.name)
head(ConsIndex) 
```

```{r}
ConsAnnualChange <- read_excel("data/Constructioncost.xls", 
                                    sheet = "Rate")
ConsAnnualChange <- pivot_longer(ConsAnnualChange,2:13,names_to = "Month", values_to = "index")
ConsAnnualChange$Month <- match(ConsAnnualChange$Month, month.name)
ConsAnnualChange$index <- as.numeric(as.character(ConsAnnualChange$index))
head(ConsAnnualChange)
```
```{r}
"House Sales data was too dirty so I clean it up in excel"
HousesalesYear <- read_excel("data/Housesales.xls", 
                                    sheet = "Year")

head(HousesalesYear) 

HousesalesMonth <- read_excel("data/Housesales.xls", 
                                     sheet = "Month")
head(HousesalesMonth) 

```




